ok nvrmd sudo is better

diff --git a/dotfiles/.bash/source/backup b/dotfiles/.bash/source/backup
--- a/dotfiles/.bash/source/backup
+++ b/dotfiles/.bash/source/backup
@@ -38,7 +38,7 @@ function backup() {
 			for folder in "${backup_folders[@]}"; do
 				path=$(readlink -f "$local_path")
 				echo -e "\x1b[30;42m Backing up: $folder \x1b[m"
-				rsync -ah --delete --info=progress2,stats1 "$HOME/$folder/" "$path/$folder/"
+				sudo rsync -ah --delete --info=progress2,stats1 "$HOME/$folder/" "$path/$folder/"
 				echo
 			done
 		fi
@@ -61,7 +61,7 @@ function backup() {
 			for folder in "${backup_folders[@]}"; do
 				path=$(readlink -f "$local_path")
 				echo -e "\x1b[30;42m Backing up: $folder \x1b[m"
-				rsync -ah --delete --info=progress2,stats1 "$path/$folder/" "$HOME/$folder/"
+				sudo rsync -ah --delete --info=progress2,stats1 "$path/$folder/" "$HOME/$folder/"
 				echo
 			done
 		fi
@@ -72,12 +72,12 @@ function backup() {
 		_get_args
 
 		if ! rclone lsd "${cloud_remote}:" >/dev/null 2>&1; then
-			echo "Error: connection to rclone drive '$cloud_remote' could not be established." >&2
+			echo "Error: connection to sudo rclone drive '$cloud_remote' could not be established." >&2
 		else
 
 			for folder in "${backup_folders[@]}"; do
 				echo -e "\x1b[30;42m Backing up: $folder \x1b[m"
-				rclone sync "$HOME/$folder/" $cloud_remote:$folder \
+				sudo rclone sync "$HOME/$folder/" $cloud_remote:$folder \
 					--progress \
 					--transfers=16 \
 					--checkers=16 \
@@ -89,6 +89,11 @@ function backup() {
 			done
 		fi
 	}
+
+	sudo -v
+	while true; do sudo -n true; sleep 60; done 2>/dev/null &
+	SUDO_KEEPALIVE_PID=$!
+	trap 'kill $SUDO_KEEPALIVE_PID' EXIT
 
 	if [ ! -f "$config_file" ]; then
 		echo "config file not found"
